# Use an official Node runtime as the base image
FROM node:21-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the dependency definition files
COPY package*.json ./
COPY pnpm-lock.yaml ./

# Install the dependencies
RUN npm install -g pnpm && pnpm install

# Copy the rest of the application files to the working directory
COPY . .

# Build the NestJS application
RUN pnpm run build

# Expose the port the app runs on
EXPOSE 3000

# Run the NestJS application
CMD ["node", "dist/main"]
